import { GovernmentService } from '../../types';

export const EDUCATION_STATE_SERVICES: GovernmentService[] = [
  {
    id: 'ap_post_matric_fee_reimbursement',
    name: 'Andhra Pradesh Post-Matric Full Fee Reimbursement (RTF)',
    department: 'Department of Social Welfare & Higher Education',
    authority: 'Government of Andhra Pradesh',
    category: 'education', secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee assistance for eligible students enrolled in accredited ITI, Polytechnic, Degree, B.Tech, and professional colleges in Andhra Pradesh.',
    benefitsSummary: '100% Tuition fee credited on quarterly schedule directly to institutional/mother bank accounts.',
    jurisdictionLevel: 'STATE', applicableStates: ['Andhra Pradesh'], residenceRequired: true,
    studyLocationEligible: false, employmentLocationEligible: false, propertyLocationEligible: false,
    agricultureLocationEligible: false, businessLocationEligible: false,
    jurisdictionConditions: 'Applicant must be a domiciled resident of Andhra Pradesh. Non-resident students studying in AP are ineligible for state-funded RTF.',
    status: 'ACTIVE', effectiveFrom: '2024-06-01',
    applicationUrl: 'https://jnanabhumi.ap.gov.in',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual household income under ₹2.50 Lakh', isMandatory: true },
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in eligible accredited professional college', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'residence_cert', 'education_marksheet', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1, title: 'Procure Integrated Caste & Income Certificate',
        description: 'Obtain digital revenue certificate from Grama/Ward Sachivalayam or Meeseva.',
        requiredDocuments: ['income_cert', 'caste_cert', 'residence_cert'], estimatedEffort: '1-3 days', isOnline: true, portalUrl: 'https://vsws.ap.gov.in',
      },
      {
        stepNumber: 2, title: 'Biometric Attendance Verification on JnanaBhumi Portal',
        description: 'Ensure 75% biometric attendance recorded at college JnanaBhumi nodal desk.',
        requiredDocuments: ['aadhaar', 'education_marksheet'], estimatedEffort: 'College verification', isOnline: false, offlineOffice: 'College JnanaBhumi Desk',
      },
      {
        stepNumber: 3, title: 'Secretariat Social Audit & Quarterly Disbursement',
        description: 'Village/Ward Education Assistant conducts social audit; quarterly tuition fee disbursed.',
        requiredDocuments: ['bank_passbook'], estimatedEffort: 'Quarterly cycle', isOnline: true,
      },
    ],
    sourceUrl: 'https://jnanabhumi.ap.gov.in', sourceAuthority: 'Government of Andhra Pradesh / JnanaBhumi Platform',
    sourceType: 'verified', sourceConfidence: 'High', lastVerified: '2026-08-30', version: '2026.1',
    tags: ['fee-reimbursement', 'andhra-pradesh', 'btech', 'education', 'jnanabhumi'],
  },
  {
    id: 'jagananna_vidya_kanuka_historical',
    name: 'Jagananna Vidya Kanuka (Historical School Kit Scheme)',
    aliases: ['JVK School Kit'],
    department: 'Department of School Education', authority: 'Government of Andhra Pradesh', category: 'education',
    description: 'Previous political-era initiative providing bilingual textbooks, notebooks, uniform cloth, and school bags to government school students.',
    benefitsSummary: 'Historical policy record. Replaced by Department of School Education Student Kit Framework.',
    jurisdictionLevel: 'STATE', applicableStates: ['Andhra Pradesh'], residenceRequired: true,
    studyLocationEligible: false, employmentLocationEligible: false, propertyLocationEligible: false,
    agricultureLocationEligible: false, businessLocationEligible: false, status: 'HISTORICAL',
    effectiveFrom: '2020-06-01', effectiveTo: '2024-05-31', replacedBy: 'AP Department of School Education Student Kit Scheme',
    officialVerificationStatus: 'HISTORICAL_ARCHIVED',
    verificationEvidence: 'GOVERNMENT_ORDER',
    eligibilityRules: [], requiredDocuments: [], steps: [],
    sourceUrl: 'https://ap.gov.in', sourceAuthority: 'Government of Andhra Pradesh',
    sourceType: 'verified', sourceConfidence: 'High', lastVerified: '2026-08-30', version: 'Historical',
    tags: ['historical', 'andhra-pradesh', 'school-kit'],
  },
  {
    id: 'tn_post_matric_scholarship',
    name: 'Tamil Nadu Government Post-Matric Scholarship (ADW & BC/MBC Welfare)',
    department: 'Adi Dravidar and Tribal Welfare / BC & MBC Welfare Dept', authority: 'Government of Tamil Nadu',
    category: 'education', secondaryCategories: ['financial_assistance'],
    description: 'Tuition and maintenance scholarship for students belonging to SC/ST/SCC/BC/MBC pursuing higher education in recognized institutions in Tamil Nadu.',
    benefitsSummary: 'Full compulsory fees covered + maintenance allowance up to ₹1,200/month.',
    jurisdictionLevel: 'STATE', applicableStates: ['Tamil Nadu'], residenceRequired: true,
    studyLocationEligible: false, employmentLocationEligible: false, propertyLocationEligible: false,
    agricultureLocationEligible: false, businessLocationEligible: false,
    jurisdictionConditions: 'Must be a permanent domiciled resident of Tamil Nadu.',
    status: 'ACTIVE', effectiveFrom: '2021-06-01',
    applicationUrl: 'https://www.tnesevai.tn.gov.in',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['OBC', 'SC', 'ST'],
    eligibilityRules: [
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'residence_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1, title: 'Obtain TN e-Sevai Community & Income Certificates',
        description: 'Procure digital certificates through TNeGA / e-Sevai portal.',
        requiredDocuments: ['income_cert', 'caste_cert'], estimatedEffort: '2-3 days', isOnline: true, portalUrl: 'https://www.tnesevai.tn.gov.in',
      },
      {
        stepNumber: 2, title: 'Submit Application on TN Scholarship Portal (UMIS)',
        description: 'Register via college admission UMIS student login.',
        requiredDocuments: ['aadhaar', 'bank_passbook'], estimatedEffort: '30 minutes', isOnline: true,
      },
    ],
    sourceUrl: 'https://www.tnesevai.tn.gov.in', sourceAuthority: 'Government of Tamil Nadu',
    sourceType: 'verified', sourceConfidence: 'High', lastVerified: '2026-08-30', version: '2026.1',
    tags: ['scholarship', 'tamil-nadu', 'education', 'post-matric'],
  },
];
