import { GovernmentService } from '../../types';

export const HEALTHCARE_CENTRAL_SERVICES: GovernmentService[] = [
  {
    id: 'pmjay_ayushman_bharat',
    name: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB PM-JAY)',
    aliases: ['Ayushman Card', 'PM-JAY Golden Card', 'Pradhan Mantri Jan Arogya Yojana'],
    department: 'National Health Authority (NHA)',
    authority: 'Ministry of Health and Family Welfare, Govt of India',
    ministry: 'Ministry of Health and Family Welfare',
    category: 'healthcare',
    secondaryCategories: ['financial_assistance', 'other'],
    description: 'Flagship national public health insurance fund providing cashless secondary and tertiary care hospitalization cover of up to ₹5,00,000 per family per year.',
    benefitsSummary: 'Cashless inpatient treatment up to ₹5,00,000/year per family across 27,000+ empaneled public and private hospitals nationwide.',
    jurisdictionLevel: 'CENTRAL',
    applicableStates: ['ALL'],
    residenceRequired: false,
    studyLocationEligible: true,
    employmentLocationEligible: true,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2018-09-23',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority'],
    eligibilityRules: [
      {
        field: 'annualIncome',
        operator: 'less_than_or_equal',
        value: 300000,
        label: 'Family socio-economic eligibility or annual household income under ₹3.0 Lakh',
        isMandatory: false,
      },
    ],
    requiredDocuments: ['aadhaar', 'ration_card', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Check PM-JAY Beneficiary Eligibility Online',
        description: 'Visit beneficiary.nha.gov.in and enter your Aadhaar or Ration Card number to verify family inclusion in the SECC database.',
        requiredDocuments: ['aadhaar', 'ration_card'],
        estimatedEffort: '5 minutes',
        isOnline: true,
        portalUrl: 'https://beneficiary.nha.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Complete e-KYC via Aadhaar OTP or Face Authentication',
        description: 'Perform biometric e-KYC using Aadhaar OTP on the NHA Beneficiary portal or via the Ayushman App.',
        requiredDocuments: ['aadhaar'],
        estimatedEffort: '10 minutes',
        isOnline: true,
        portalUrl: 'https://beneficiary.nha.gov.in',
      },
      {
        stepNumber: 3,
        title: 'Download and Print Verified Ayushman Card',
        description: 'Upon automated or district approval, download your PVC-ready Ayushman Card PDF featuring the unique ABHA / PMJAY ID.',
        requiredDocuments: [],
        estimatedEffort: 'Instant download',
        isOnline: true,
        portalUrl: 'https://beneficiary.nha.gov.in',
      },
      {
        stepNumber: 4,
        title: 'Avail Cashless Hospitalization at Any Empaneled Network Hospital',
        description: 'Present your Ayushman Card at the Ayushman Mitra desk in any empaneled government or private hospital for cashless treatment.',
        requiredDocuments: ['aadhaar'],
        estimatedEffort: 'At time of admission',
        isOnline: false,
        offlineOffice: 'Hospital Ayushman Mitra Nodal Desk',
      },
    ],
    sourceUrl: 'https://pmjay.gov.in',
    applicationUrl: 'https://beneficiary.nha.gov.in',
    sourceAuthority: 'National Health Authority, Ministry of Health and Family Welfare',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['healthcare', 'pmjay', 'ayushman-bharat', 'health-insurance', 'cashless-hospital', 'central'],
  },
  {
    id: 'pm_surya_ghar_muft_bijli',
    name: 'PM - Surya Ghar: Muft Bijli Yojana',
    aliases: ['PM Surya Ghar', 'National Rooftop Solar Scheme', 'Muft Bijli Yojana'],
    department: 'Department of Renewable Energy',
    authority: 'Ministry of New and Renewable Energy (MNRE), Govt of India',
    ministry: 'Ministry of New and Renewable Energy',
    category: 'financial_assistance',
    secondaryCategories: ['other', 'housing', 'business'],
    description: 'National rooftop solar scheme providing direct central financial assistance (DBT subsidy) of up to ₹78,000 for residential households to install solar power systems, ensuring up to 300 units of free electricity monthly.',
    benefitsSummary: 'Direct bank transfer (DBT) subsidy of up to ₹78,000 for 3kW solar installation + up to 300 units free monthly solar power.',
    jurisdictionLevel: 'CENTRAL',
    applicableStates: ['ALL'],
    residenceRequired: false,
    studyLocationEligible: false,
    employmentLocationEligible: false,
    propertyLocationEligible: true,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2024-02-13',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority'],
    eligibilityRules: [
      {
        field: 'isBusinessOwner',
        operator: 'boolean_true',
        value: false,
        label: 'Residential household installation (non-commercial tariff)',
        isMandatory: false,
      },
    ],
    requiredDocuments: ['aadhaar', 'electricity_bill', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Register on National Solar Rooftop Portal',
        description: 'Create account on pmsuryaghar.gov.in by selecting your State, Electricity Distribution Company (DISCOM), and Consumer Account Number.',
        requiredDocuments: ['electricity_bill'],
        estimatedEffort: '15 minutes',
        isOnline: true,
        portalUrl: 'https://pmsuryaghar.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Apply for Rooftop Solar Feasibility Approval',
        description: 'Submit technical application for desired solar capacity (1kW to 3kW+). DISCOM reviews technical grid feasibility online.',
        requiredDocuments: ['electricity_bill', 'aadhaar'],
        estimatedEffort: '3-7 days for DISCOM review',
        isOnline: true,
        portalUrl: 'https://pmsuryaghar.gov.in',
      },
      {
        stepNumber: 3,
        title: 'Installation through Registered Vendor and Net Metering',
        description: 'Select an empaneled vendor from the portal for installation; DISCOM installs bidirectional net meter after commissioning.',
        requiredDocuments: [],
        estimatedEffort: '7-14 days',
        isOnline: false,
      },
      {
        stepNumber: 4,
        title: 'Receive DBT Subsidy Directly into Bank Account',
        description: 'Submit bank account details and cancelled cheque on portal. Central subsidy up to ₹78,000 credited via PFMS within 30 days of inspection.',
        requiredDocuments: ['bank_passbook'],
        estimatedEffort: 'Direct bank credit within 30 days',
        isOnline: true,
        portalUrl: 'https://pmsuryaghar.gov.in',
      },
    ],
    sourceUrl: 'https://pmsuryaghar.gov.in',
    applicationUrl: 'https://pmsuryaghar.gov.in',
    sourceAuthority: 'Ministry of New and Renewable Energy (MNRE)',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['solar', 'energy', 'pmsuryaghar', 'subsidy', 'electricity', 'central', 'rooftop'],
  },
];
