import { GovernmentService } from '../../types';

export const STATE_SCHEMES: GovernmentService[] = [
  // 1. Andhra Pradesh
  {
    id: 'ap_annadata_sukhibhava_rythu_bharosa',
    name: 'Andhra Pradesh Annadata Sukhibhava Scheme',
    aliases: ['Annadata Sukhibhava', 'YSR Rythu Bharosa (Historical Name)', 'AP Annadata Sukhibhava'],
    department: 'Department of Agriculture and Farmers Welfare',
    authority: 'Government of Andhra Pradesh',
    category: 'agriculture',
    secondaryCategories: ['financial_assistance'],
    description: 'Input financial assistance for land-owning farmers and tenant farmers in Andhra Pradesh to support seasonal crop cultivation and farm investment.',
    benefitsSummary: 'Annual direct benefit transfer of ₹20,000 (including Central PM-KISAN ₹6,000) in scheduled installments into Aadhaar-linked bank accounts.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Andhra Pradesh'],
    residenceRequired: false,
    agricultureLocationEligible: true,
    propertyLocationEligible: false,
    studyLocationEligible: false,
    employmentLocationEligible: false,
    businessLocationEligible: false,
    jurisdictionConditions: 'Applicant must be an agricultural land cultivator in Andhra Pradesh. Under the NDA/TDP administration, the scheme was renamed Annadata Sukhibhava providing enhanced input subsidy.',
    status: 'ACTIVE',
    effectiveFrom: '2019-10-15',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isFarmer', operator: 'boolean_true', value: true, label: 'Registered farmer or cultivator in Andhra Pradesh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'pattadar_passbook', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Verify Land Details on AP e-Crop Booking (e-Panta / Annadata Sukhibhava)',
        description: 'Ensure agricultural parcel cultivation is verified by Village Agriculture Assistant on the AP e-Crop portal.',
        requiredDocuments: ['pattadar_passbook'],
        estimatedEffort: '1-2 days',
        isOnline: true,
        portalUrl: 'https://annadathasukhibhava.ap.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Authentication at Rythu Bharosa Kendram (RBK)',
        description: 'Complete biometric/iris authentication at the local Village Rythu Bharosa Kendram.',
        requiredDocuments: ['aadhaar', 'bank_passbook'],
        estimatedEffort: '15 minutes',
        isOnline: false,
        offlineOffice: 'Village Rythu Bharosa Kendram (RBK)',
      },
    ],
    sourceUrl: 'https://annadathasukhibhava.ap.gov.in',
    applicationUrl: 'https://annadathasukhibhava.ap.gov.in',
    sourceAuthority: 'Department of Agriculture & Farmers Welfare, Government of Andhra Pradesh',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['agriculture', 'farmer', 'annadata-sukhibhava', 'rythu-bharosa', 'andhra-pradesh', 'dbt'],
  },

  // 2. Telangana
  {
    id: 'telangana_epass_post_matric',
    name: 'Telangana ePASS Post-Matric Tuition Fee Reimbursement & Scholarship',
    aliases: ['Telangana ePASS', 'TS RTF and MTF'],
    department: 'Backward Classes Welfare & SC/ST Welfare Departments',
    authority: 'Government of Telangana',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee reimbursement (RTF) and maintenance fee (MTF) for eligible domiciled students studying in accredited colleges across Telangana.',
    benefitsSummary: '100% tuition fee reimbursement credited to college accounts + monthly maintenance allowance up to ₹2,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Telangana'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    jurisdictionConditions: 'Must be a domiciled resident of Telangana enrolled in post-matric studies.',
    status: 'ACTIVE',
    effectiveFrom: '2014-06-02',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'EWS', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric degree/diploma course in Telangana', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 200000, label: 'Family annual income under ₹2.0 Lakh (₹1.5L for rural)', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC', 'EWS', 'Minority'], label: 'Designated for SC, ST, BC, EBC, or Minority categories', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'education_marksheet', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Procure MeeSeva Caste & Income Certificates',
        description: 'Obtain current digitally signed certificates from Telangana MeeSeva centers.',
        requiredDocuments: ['income_cert', 'caste_cert'],
        estimatedEffort: '2-3 days',
        isOnline: true,
        portalUrl: 'https://telanganaepass.cgg.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Apply Online via Telangana ePASS Portal',
        description: 'Fill student registration on telanganaepass.cgg.gov.in using SSC hall ticket and Aadhaar number.',
        requiredDocuments: ['aadhaar', 'education_marksheet', 'bank_passbook'],
        estimatedEffort: '30 minutes',
        isOnline: true,
        portalUrl: 'https://telanganaepass.cgg.gov.in',
      },
    ],
    sourceUrl: 'https://telanganaepass.cgg.gov.in',
    applicationUrl: 'https://telanganaepass.cgg.gov.in',
    sourceAuthority: 'Government of Telangana Welfare Departments',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'education', 'telangana', 'epass', 'fee-reimbursement'],
  },

  // 3. Tamil Nadu
  {
    id: 'tn_pudhumai_penn_scheme',
    name: 'Tamil Nadu Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn)',
    aliases: ['Pudhumai Penn Scheme', 'TN Moovalur Scheme'],
    department: 'Department of Social Welfare and Women Empowerment',
    authority: 'Government of Tamil Nadu',
    category: 'education',
    secondaryCategories: ['financial_assistance', 'women_child'],
    description: 'Financial assistance scheme to encourage female students from government schools in Tamil Nadu to pursue undergraduate degrees, diplomas, and ITI courses.',
    benefitsSummary: 'Direct monthly financial incentive of ₹1,000 deposited into the student bank account until course completion.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Tamil Nadu'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2022-09-05',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in undergraduate degree or diploma in Tamil Nadu', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'school_bonafide', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Verification of Government School Study (Classes 6-12)',
        description: 'Upload EMIS student ID and bonafide from Tamil Nadu government school on UMIS portal.',
        requiredDocuments: ['school_bonafide'],
        estimatedEffort: '1 day',
        isOnline: true,
        portalUrl: 'https://www.tnesevai.tn.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Direct Monthly DBT Bank Sanction',
        description: 'College nodal officer validates admission; ₹1,000 monthly allowance credited via PFMS DBT.',
        requiredDocuments: ['bank_passbook'],
        estimatedEffort: 'Monthly cycle',
        isOnline: true,
        portalUrl: 'https://www.tnesevai.tn.gov.in',
      },
    ],
    sourceUrl: 'https://www.tnesevai.tn.gov.in',
    applicationUrl: 'https://www.tnesevai.tn.gov.in',
    sourceAuthority: 'Government of Tamil Nadu',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'tamil-nadu', 'women', 'education', 'pudhumai-penn'],
  },

  // 4. Karnataka
  {
    id: 'karnataka_ssp_post_matric',
    name: 'Karnataka State Scholarship Portal (SSP) Post-Matric Scholarship',
    aliases: ['Karnataka SSP', 'SSP Post Matric'],
    department: 'Social Welfare, Tribal Welfare, Backward Classes & Minorities Welfare Departments',
    authority: 'Government of Karnataka',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Integrated digital post-matric scholarship and fee concession system for Karnataka domiciled students studying in professional, technical, and general higher education institutions.',
    benefitsSummary: 'Full tuition fee reimbursement + annual maintenance stipend up to ₹10,000 depending on course category.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Karnataka'],
    residenceRequired: false,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2019-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'EWS', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized post-matric course in Karnataka', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC', 'EWS', 'Minority'], label: 'Reserved for SC, ST, OBC, EWS or Minority students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'education_marksheet', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Create SSP Student Account with Kutumba ID',
        description: 'Register on ssp.postmatric.karnataka.gov.in using Aadhaar and Karnataka Kutumba Family ID.',
        requiredDocuments: ['aadhaar'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://ssp.postmatric.karnataka.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Submit E-Attestation of College Admission',
        description: 'Get college admission and fee receipt e-attested by institutional verification officer.',
        requiredDocuments: ['education_marksheet'],
        estimatedEffort: '1-3 business days',
        isOnline: true,
        portalUrl: 'https://ssp.postmatric.karnataka.gov.in',
      },
    ],
    sourceUrl: 'https://ssp.postmatric.karnataka.gov.in',
    applicationUrl: 'https://ssp.postmatric.karnataka.gov.in',
    sourceAuthority: 'Government of Karnataka',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'karnataka', 'education', 'ssp', 'post-matric'],
  },

  // 5. Kerala
  {
    id: 'kerala_e_grantz_post_matric',
    name: 'Kerala E-Grantz 3.0 Post-Matric Educational Assistance',
    aliases: ['Kerala E-Grantz', 'E-Grantz Kerala'],
    department: 'Scheduled Castes Development & Backward Classes Development Departments',
    authority: 'Government of Kerala',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Comprehensive digital welfare scheme providing post-matric educational scholarships, tuition reimbursement, and boarding grants to students in Kerala.',
    benefitsSummary: '100% tuition and examination fees paid directly to colleges + monthly pocket money / boarding grants.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Kerala'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2015-06-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Kerala', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual household income under ₹2.5 Lakh for OBC/General (no ceiling for SC/ST)', isMandatory: false },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC', 'EWS'], label: 'Reserved for SC, ST, OEC, OBC, or EWS students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on E-Grantz 3.0 Portal',
        description: 'Register and enter academic details on egrantz.kerala.gov.in using Aadhaar authentication.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '30 minutes',
        isOnline: true,
        portalUrl: 'https://egrantz.kerala.gov.in',
      },
    ],
    sourceUrl: 'https://egrantz.kerala.gov.in',
    applicationUrl: 'https://egrantz.kerala.gov.in',
    sourceAuthority: 'Government of Kerala SC Development Department',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'kerala', 'education', 'egrantz'],
  },

  // 6. Maharashtra
  {
    id: 'maharashtra_mahadbt_post_matric',
    name: 'Maharashtra MahaDBT Rajarshi Chhatrapati Shahu Maharaj Tuition Fee Scholarship',
    aliases: ['MahaDBT', 'EBC Scholarship Maharashtra', 'RCSM Scholarship'],
    department: 'Directorate of Higher Education & Social Justice Department',
    authority: 'Government of Maharashtra',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee waiver and examination fee reimbursement for students from economically weaker sections, OBC, SC, ST, and general categories enrolled in higher education in Maharashtra.',
    benefitsSummary: '50% to 100% reimbursement of approved tuition and exam fees in government and private un-aided colleges.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Maharashtra'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2018-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized higher education course in Maharashtra', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 800000, label: 'Annual family income must not exceed ₹8.0 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'domicile_cert', 'education_marksheet', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Register on Aaple Sarkar MahaDBT Portal',
        description: 'Complete registration on mahadbt.maharashtra.gov.in using Aadhaar OTP verification.',
        requiredDocuments: ['aadhaar'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://mahadbt.maharashtra.gov.in',
      },
      {
        stepNumber: 2,
        title: 'Upload Domicile and Income Proof',
        description: 'Submit Tehsildar-issued domicile certificate and revenue income certificate.',
        requiredDocuments: ['domicile_cert', 'income_cert'],
        estimatedEffort: '15 minutes',
        isOnline: true,
        portalUrl: 'https://mahadbt.maharashtra.gov.in',
      },
    ],
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    applicationUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceAuthority: 'Government of Maharashtra',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'maharashtra', 'education', 'mahadbt', 'ebc'],
  },

  // 7. Uttar Pradesh
  {
    id: 'up_scholarship_fee_reimbursement',
    name: 'Uttar Pradesh Post-Matric Scholarship & Fee Reimbursement Online System',
    aliases: ['UP Scholarship', 'Saksham UP Scholarship'],
    department: 'Social Welfare, Backward Class Welfare & Minority Welfare Departments',
    authority: 'Government of Uttar Pradesh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Direct scholarship and non-refundable fee reimbursement for post-matric and higher education students belonging to General, OBC, SC, ST, and Minority communities domiciled in UP.',
    benefitsSummary: 'Full reimbursement of non-refundable tuition fees up to ₹50,000+ per year + maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Uttar Pradesh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Uttar Pradesh', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh for SC/ST or ₹2 Lakh for General/OBC', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'education_marksheet', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Complete Student Registration on UP Scholarship Portal',
        description: 'Register with High School roll number and Aadhaar OTP on scholarship.up.gov.in.',
        requiredDocuments: ['aadhaar', 'education_marksheet'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://scholarship.up.gov.in',
      },
    ],
    sourceUrl: 'https://scholarship.up.gov.in',
    applicationUrl: 'https://scholarship.up.gov.in',
    sourceAuthority: 'Government of Uttar Pradesh',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'uttar-pradesh', 'education', 'fee-reimbursement'],
  },

  // 8. West Bengal
  {
    id: 'wb_oasis_scholarship',
    name: 'West Bengal OASIS Post-Matric Scholarship for SC/ST/OBC',
    aliases: ['WB OASIS', 'OASIS Scholarship'],
    department: 'Backward Classes Welfare and Tribal Development Department',
    authority: 'Government of West Bengal',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric financial assistance scholarship scheme for SC, ST, and OBC students in West Bengal to pursue secondary, collegiate, and professional higher studies.',
    benefitsSummary: 'Maintenance grant up to ₹1,200/month + full compulsory institutional tuition fee reimbursement.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['West Bengal'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2015-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in West Bengal', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for SC, ST, and OBC students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Submit Online Application on OASIS Portal',
        description: 'Complete registration on oasis.gov.in and submit acknowledgment copy to Block BDO or Sub-Divisional Officer.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '30 minutes online + institutional endorsement',
        isOnline: true,
        portalUrl: 'https://oasis.gov.in',
      },
    ],
    sourceUrl: 'https://oasis.gov.in',
    applicationUrl: 'https://oasis.gov.in',
    sourceAuthority: 'Government of West Bengal',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'west-bengal', 'education', 'oasis'],
  },

  // 9. Gujarat
  {
    id: 'gujarat_digital_gujarat_scholarship',
    name: 'Digital Gujarat Post-Matric Scholarship & Higher Education Assistance',
    aliases: ['Digital Gujarat Scholarship'],
    department: 'Social Justice & Empowerment Department',
    authority: 'Government of Gujarat',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric scholarship and financial assistance scheme for students belonging to SC, ST, SEBC, and EWS categories studying in Gujarat.',
    benefitsSummary: '100% approved tuition fee reimbursement + annual maintenance stipend up to ₹12,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Gujarat'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-04-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Gujarat', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh for reserved or ₹2.0 Lakh for EWS', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Digital Gujarat Portal',
        description: 'Login to digitalgujarat.gov.in and choose Higher Education Scholarship scheme.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://www.digitalgujarat.gov.in',
      },
    ],
    sourceUrl: 'https://www.digitalgujarat.gov.in',
    applicationUrl: 'https://www.digitalgujarat.gov.in',
    sourceAuthority: 'Government of Gujarat',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'gujarat', 'education', 'digital-gujarat'],
  },

  // 10. Rajasthan
  {
    id: 'rajasthan_uttar_matric_scholarship',
    name: 'Rajasthan Uttar Matric (Post-Matric) Scholarship (SJMS Portal)',
    aliases: ['Rajasthan Uttar Matric', 'SJMS Scholarship'],
    department: 'Social Justice and Empowerment Department (SJED)',
    authority: 'Government of Rajasthan',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Comprehensive scholarship and tuition assistance scheme for SC, ST, SBC, EBC, and DNT students pursuing higher education in Rajasthan.',
    benefitsSummary: '100% tuition and registration fees refunded + monthly allowance up to ₹1,200.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Rajasthan'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-06-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'EWS', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized higher education in Rajasthan', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC', 'EWS', 'Minority'], label: 'Reserved for SC, ST, SBC, EBC, or Minority categories', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'jan_aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Jan Aadhaar on SJMS Portal',
        description: 'Access sjmsnew.rajasthan.gov.in using SSO ID and Jan Aadhaar authentication.',
        requiredDocuments: ['jan_aadhaar', 'income_cert'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://sjmsnew.rajasthan.gov.in',
      },
    ],
    sourceUrl: 'https://sjmsnew.rajasthan.gov.in',
    applicationUrl: 'https://sjmsnew.rajasthan.gov.in',
    sourceAuthority: 'Government of Rajasthan SJED',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'rajasthan', 'education', 'sjed', 'uttar-matric'],
  },

  // 11. Madhya Pradesh
  {
    id: 'mp_mptaas_scholarship',
    name: 'Madhya Pradesh MPTAAS Post-Matric Scholarship System',
    aliases: ['MPTAAS', 'MP Post Matric Scholarship'],
    department: 'Tribal Affairs and Scheduled Caste Welfare Department',
    authority: 'Government of Madhya Pradesh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Direct benefit transfer portal providing post-matric scholarship, fee waiver, and hostel allowances to SC and ST students in Madhya Pradesh.',
    benefitsSummary: 'Full tuition and statutory fees covered + monthly maintenance allowance up to ₹1,500.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Madhya Pradesh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2018-09-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Madhya Pradesh', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 300000, label: 'Annual household income under ₹3.0 Lakh for OBC/general quotas (relaxed for SC/ST)', isMandatory: false },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for SC, ST, or OBC students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'samagra_id', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through MPTAAS Profile',
        description: 'Login to tribal.mp.gov.in/mptaas using Samagra ID and Aadhaar e-KYC.',
        requiredDocuments: ['aadhaar', 'samagra_id'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://www.tribal.mp.gov.in/mptaas',
      },
    ],
    sourceUrl: 'https://www.tribal.mp.gov.in/mptaas',
    applicationUrl: 'https://www.tribal.mp.gov.in/mptaas',
    sourceAuthority: 'Government of Madhya Pradesh Tribal Affairs',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'madhya-pradesh', 'education', 'mptaas'],
  },

  // 12. Punjab
  {
    id: 'punjab_dr_ambedkar_scholarship',
    name: 'Punjab Dr. B.R. Ambedkar Post-Matric Scholarship Scheme',
    aliases: ['Punjab PMS SC', 'Dr Ambedkar Scholarship Punjab'],
    department: 'Department of Social Justice, Empowerment and Minorities',
    authority: 'Government of Punjab',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'State-sponsored 100% fee waiver and stipend scheme for Scheduled Caste and Backward Class students pursuing post-matric studies in Punjab.',
    benefitsSummary: '100% tuition and examination fee exemption in accredited colleges + monthly stipend.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Punjab'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2021-04-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'OBC', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Punjab', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income must not exceed ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'OBC', 'EWS'], label: 'Reserved for SC, BC, or EWS students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Dr. Ambedkar Scholarship Portal',
        description: 'Complete registration on scholarships.punjab.gov.in using Aadhaar verification.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://scholarships.punjab.gov.in',
      },
    ],
    sourceUrl: 'https://scholarships.punjab.gov.in',
    applicationUrl: 'https://scholarships.punjab.gov.in',
    sourceAuthority: 'Government of Punjab',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'punjab', 'education', 'dr-ambedkar'],
  },

  // 13. Haryana
  {
    id: 'haryana_saral_post_matric',
    name: 'Haryana Har-Chhatravratti Post-Matric Scholarship Portal',
    aliases: ['Haryana Har Chhatravratti', 'Antyodaya Saral Haryana Scholarship'],
    department: 'Department of Higher Education & Welfare of SC and BC Department',
    authority: 'Government of Haryana',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Centralized single-window scholarship system covering SC, BC, and Meritorious students studying in Haryana institutions.',
    benefitsSummary: '100% reimbursement of tuition fees + annual maintenance grant up to ₹14,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Haryana'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2020-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Haryana', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh based on Parivar Pehchan Patra (PPP)', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'parivar_pehchan_patra', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Parivar Pehchan Patra (PPP)',
        description: 'Verify household income on harchhatravratti.highereduhry.ac.in using Family ID (PPP).',
        requiredDocuments: ['parivar_pehchan_patra'],
        estimatedEffort: '15 minutes',
        isOnline: true,
        portalUrl: 'https://harchhatravratti.highereduhry.ac.in',
      },
    ],
    sourceUrl: 'https://saralharyana.gov.in',
    applicationUrl: 'https://harchhatravratti.highereduhry.ac.in',
    sourceAuthority: 'Government of Haryana',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'haryana', 'education', 'harchhatravratti'],
  },

  // 14. Bihar
  {
    id: 'bihar_pmsonline_scholarship',
    name: 'Bihar Post-Matric Scholarship (PMS Portal)',
    aliases: ['Bihar PMS', 'pmsonline Bihar'],
    department: 'BC & EBC Welfare / SC & ST Welfare Department',
    authority: 'Government of Bihar',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric educational assistance for students belonging to SC, ST, BC, and EBC categories domiciled in Bihar and studying in recognized institutions.',
    benefitsSummary: 'Full tuition and compulsory fees reimbursement credited through DBT into Aadhaar-seeded accounts.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Bihar'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2021-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Bihar or authorized out-of-state institutes', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 300000, label: 'Annual family income under ₹3.0 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['OBC', 'SC', 'ST', 'EWS'], label: 'Reserved for SC, ST, BC, and EBC categories', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Bihar PMS Portal',
        description: 'Register and submit college bonafide on pmsonline.bih.nic.in.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '30 minutes',
        isOnline: true,
        portalUrl: 'https://pmsonline.bih.nic.in',
      },
    ],
    sourceUrl: 'https://pmsonline.bih.nic.in',
    applicationUrl: 'https://pmsonline.bih.nic.in',
    sourceAuthority: 'Government of Bihar Welfare Departments',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'bihar', 'education', 'pmsonline'],
  },

  // 15. Odisha
  {
    id: 'odisha_state_scholarship',
    name: 'Odisha State Scholarship Portal (Post-Matric & Medhabruti)',
    aliases: ['Odisha Scholarship Portal', 'Medhabruti Odisha'],
    department: 'ST & SC Development and Higher Education Department',
    authority: 'Government of Odisha',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Unified state portal delivering post-matric, e-Medhabruti, and merit-cum-poverty scholarships for domiciled students in Odisha.',
    benefitsSummary: 'Annual scholarship assistance from ₹10,000 to ₹25,000 + full tuition reimbursement.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Odisha'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2020-10-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized higher education in Odisha', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh for welfare categories', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Odisha State Scholarship Portal',
        description: 'Complete registration on scholarship.odisha.gov.in using Aadhaar authentication.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://scholarship.odisha.gov.in',
      },
    ],
    sourceUrl: 'https://scholarship.odisha.gov.in',
    applicationUrl: 'https://scholarship.odisha.gov.in',
    sourceAuthority: 'Government of Odisha',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'odisha', 'education', 'post-matric'],
  },

  // 16. Assam
  {
    id: 'assam_pragyan_bharati',
    name: 'Assam Pragyan Bharati & Post-Matric Scholarship Scheme',
    aliases: ['Pragyan Bharati Assam', 'Assam Post Matric'],
    department: 'Department of Higher Education & Welfare of Plain Tribes and Backward Classes',
    authority: 'Government of Assam',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Free admission, textbook assistance, and post-matric scholarship for students domiciled in Assam studying in higher secondary, degree, and polytechnic colleges.',
    benefitsSummary: '100% free institutional admission/tuition fee waiver + textbook allowance + post-matric maintenance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Assam'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2020-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in government/provincialised college in Assam', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 200000, label: 'Parental annual income under ₹2.0 Lakh for fee waiver', isMandatory: false },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'prc_assam', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Assam Higher Education Portal',
        description: 'Submit admission fee waiver application on directorateofhighereducation.assam.gov.in.',
        requiredDocuments: ['income_cert', 'prc_assam'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://directorateofhighereducation.assam.gov.in',
      },
    ],
    sourceUrl: 'https://onlinebcwd.assam.gov.in',
    applicationUrl: 'https://directorateofhighereducation.assam.gov.in',
    sourceAuthority: 'Government of Assam',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'assam', 'education', 'pragyan-bharati'],
  },

  // 17. Jharkhand
  {
    id: 'jharkhand_ekalyan_post_matric',
    name: 'Jharkhand e-Kalyan Post-Matric Scholarship Scheme',
    aliases: ['e-Kalyan Jharkhand', 'Jharkhand Post Matric'],
    department: 'Scheduled Tribe, Scheduled Caste, Minority and Backward Class Welfare Department',
    authority: 'Government of Jharkhand',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Flagship higher education welfare scheme reimbursing institutional fees and providing living allowances to SC, ST, and BC students of Jharkhand.',
    benefitsSummary: 'Full tuition fee reimbursement + monthly maintenance allowance up to ₹1,200.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Jharkhand'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2015-06-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Jharkhand', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh for SC/ST or ₹1.5 Lakh for BC', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for SC, ST, or BC students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Jharkhand e-Kalyan Portal',
        description: 'Complete student application on ekalyan.cgg.gov.in using Aadhaar-linked OTP.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '30 minutes',
        isOnline: true,
        portalUrl: 'https://ekalyan.cgg.gov.in',
      },
    ],
    sourceUrl: 'https://ekalyan.cgg.gov.in',
    applicationUrl: 'https://ekalyan.cgg.gov.in',
    sourceAuthority: 'Government of Jharkhand Welfare Department',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'jharkhand', 'education', 'ekalyan'],
  },

  // 18. Chhattisgarh
  {
    id: 'chhattisgarh_post_matric',
    name: 'Chhattisgarh Post-Matric State Scholarship Portal',
    aliases: ['CG Post Matric', 'Chhattisgarh Scholarship Portal'],
    department: 'Tribal and Scheduled Caste Development Department',
    authority: 'Government of Chhattisgarh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee reimbursement and maintenance grant for ST, SC, and OBC students domiciled in Chhattisgarh.',
    benefitsSummary: '100% compulsory non-refundable fees covered + monthly maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Chhattisgarh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized higher education in Chhattisgarh', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh for SC/ST or ₹1.0 Lakh for OBC', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for SC, ST, or OBC students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on CG Scholarship Portal',
        description: 'Complete registration on postmatric-scholarship.cg.nic.in.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://postmatric-scholarship.cg.nic.in',
      },
    ],
    sourceUrl: 'https://postmatric-scholarship.cg.nic.in',
    applicationUrl: 'https://postmatric-scholarship.cg.nic.in',
    sourceAuthority: 'Government of Chhattisgarh',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'chhattisgarh', 'education', 'post-matric'],
  },

  // 19. Uttarakhand
  {
    id: 'uttarakhand_ekalyan_scholarship',
    name: 'Uttarakhand Social Welfare Post-Matric Scholarship Portal',
    aliases: ['Uttarakhand Post Matric', 'e-Kalyan Uttarakhand'],
    department: 'Social Welfare Department',
    authority: 'Government of Uttarakhand',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric scholarship and fee assistance for SC, ST, OBC, and EWS students domiciled in Uttarakhand.',
    benefitsSummary: 'Full tuition fee reimbursement + annual maintenance stipend up to ₹10,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Uttarakhand'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in higher education in Uttarakhand', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh for SC/ST or ₹1.5 Lakh for OBC', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Uttarakhand e-Kalyan Portal',
        description: 'Complete registration on ekalyan.uk.gov.in using Aadhaar authentication.',
        requiredDocuments: ['aadhaar', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://ekalyan.uk.gov.in',
      },
    ],
    sourceUrl: 'https://ekalyan.uk.gov.in',
    applicationUrl: 'https://ekalyan.uk.gov.in',
    sourceAuthority: 'Government of Uttarakhand Social Welfare Department',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'uttarakhand', 'education', 'ekalyan'],
  },

  // 20. Himachal Pradesh
  {
    id: 'himachal_epass_scholarship',
    name: 'Himachal Pradesh ePASS Post-Matric Scholarship Scheme',
    aliases: ['HP ePASS', 'HP Post Matric'],
    department: 'Directorate of Higher Education',
    authority: 'Government of Himachal Pradesh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Centrally sponsored and state-funded post-matric scholarship schemes for SC, ST, OBC, and General EWS students of Himachal Pradesh.',
    benefitsSummary: '100% compulsory course fees reimbursed + maintenance stipend.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Himachal Pradesh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2015-05-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized higher education in Himachal Pradesh', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh for SC/ST or ₹1.5 Lakh for OBC', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'bonafide_himachali', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on HP ePASS Portal',
        description: 'Complete registration on hpepass.cgg.gov.in with Bonafide Himachali certificate.',
        requiredDocuments: ['aadhaar', 'bonafide_himachali', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://hpepass.cgg.gov.in',
      },
    ],
    sourceUrl: 'https://hpepass.cgg.gov.in',
    applicationUrl: 'https://hpepass.cgg.gov.in',
    sourceAuthority: 'Government of Himachal Pradesh Directorate of Higher Education',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'himachal-pradesh', 'education', 'hpepass'],
  },

  // 21. Goa
  {
    id: 'goa_tribal_post_matric',
    name: 'Goa Gagan Bharari Shiksha Yojana and Post-Matric Tribal Scholarship',
    aliases: ['Goa Gagan Bharari', 'Goa Tribal Scholarship'],
    department: 'Directorate of Tribal Welfare & Social Welfare Department',
    authority: 'Government of Goa',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Educational financial support for ST and SC students in Goa pursuing higher secondary, degree, medical, and professional technical education.',
    benefitsSummary: 'Annual financial support up to ₹15,000 to ₹35,000 directly deposited for books, fees, and instruments.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Goa'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-06-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric course in Goa', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 300000, label: 'Family annual income under ₹3.0 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for ST, SC, or OBC communities of Goa', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'domicile_goa', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply via Goa Services Portal',
        description: 'Access services.goa.gov.in under Directorate of Tribal Welfare and submit application.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://services.goa.gov.in',
      },
    ],
    sourceUrl: 'https://services.goa.gov.in',
    applicationUrl: 'https://services.goa.gov.in',
    sourceAuthority: 'Government of Goa Directorate of Tribal Welfare',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'goa', 'education', 'tribal'],
  },

  // 22. Tripura
  {
    id: 'tripura_post_matric_scholarship',
    name: 'Tripura State Post-Matric Welfare Scholarship Scheme',
    aliases: ['Tripura Post Matric'],
    department: 'Directorate of Tribal Welfare & Higher Education Department',
    authority: 'Government of Tripura',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric educational assistance for tribal, SC, and backward community students domiciled in Tripura.',
    benefitsSummary: 'Full tuition fee reimbursement + monthly maintenance allowance up to ₹1,200.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Tripura'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'General'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Tripura', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'prtc_tripura', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through State Portal / NSP Tripura Counter',
        description: 'Complete verification on tripura.gov.in with Permanent Resident of Tripura Certificate (PRTC).',
        requiredDocuments: ['aadhaar', 'prtc_tripura', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://tripura.gov.in',
      },
    ],
    sourceUrl: 'https://tripura.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Tripura',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'tripura', 'education', 'post-matric'],
  },

  // 23. Meghalaya
  {
    id: 'meghalaya_post_matric_scholarship',
    name: 'Meghalaya Post-Matric State Scholarship for Tribal Students',
    aliases: ['Meghalaya Tribal Scholarship'],
    department: 'Directorate of Higher & Technical Education',
    authority: 'Government of Meghalaya',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric scholarship scheme for Scheduled Tribe and Scheduled Caste students domiciled in Meghalaya.',
    benefitsSummary: 'Compulsory non-refundable tuition and exam fees covered + monthly maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Meghalaya'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST', 'SC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Meghalaya', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['ST', 'SC'], label: 'Designated for ST and SC students of Meghalaya', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Meghalaya Education Portal',
        description: 'Complete registration on megeducation.gov.in with tribal domicile certification.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://megeducation.gov.in',
      },
    ],
    sourceUrl: 'https://megeducation.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Meghalaya DHTE',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'meghalaya', 'education', 'tribal'],
  },

  // 24. Manipur
  {
    id: 'manipur_post_matric_scholarship',
    name: 'Manipur Post-Matric Scholarship for Scheduled Tribes & Other Communities',
    aliases: ['Manipur PMS'],
    department: 'Tribal Affairs and Hills Department & Directorate of Higher Education',
    authority: 'Government of Manipur',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric financial assistance for ST, SC, and OBC students domiciled in Manipur.',
    benefitsSummary: 'Reimbursement of statutory institutional tuition fees + maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Manipur'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST', 'SC', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric course in Manipur', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['ST', 'SC', 'OBC'], label: 'Reserved for ST, SC, or OBC students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Manipur State Portal',
        description: 'Complete registration on manipur.gov.in with tribal affairs verification.',
        requiredDocuments: ['aadhaar', 'income_cert', 'caste_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://manipur.gov.in',
      },
    ],
    sourceUrl: 'https://manipur.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Manipur',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'manipur', 'education', 'post-matric'],
  },

  // 25. Nagaland
  {
    id: 'nagaland_post_matric_scholarship',
    name: 'Nagaland Post-Matric Scholarship for ST Students',
    aliases: ['Nagaland PMS ST'],
    department: 'Department of Higher Education',
    authority: 'Government of Nagaland',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric scholarship scheme for Indigenous Scheduled Tribe students of Nagaland pursuing post-matric courses within and outside the state.',
    benefitsSummary: 'Tuition fee support + monthly maintenance grant up to ₹1,400 depending on course category.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Nagaland'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual parental income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'equals', value: 'ST', label: 'Indigenous Scheduled Tribe of Nagaland', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'indigenous_cert_nagaland', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Nagaland Higher Education Portal',
        description: 'Complete registration on highereducation.nagaland.gov.in with Indigenous Inhabitant Certificate.',
        requiredDocuments: ['aadhaar', 'indigenous_cert_nagaland', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://highereducation.nagaland.gov.in',
      },
    ],
    sourceUrl: 'https://highereducation.nagaland.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Nagaland Department of Higher Education',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'nagaland', 'education', 'st-scholarship'],
  },

  // 26. Mizoram
  {
    id: 'mizoram_post_matric_scholarship',
    name: 'Mizoram Post-Matric Higher Education Scholarship',
    aliases: ['Mizoram PMS'],
    department: 'Higher and Technical Education Department',
    authority: 'Government of Mizoram',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'State scholarship supporting Scheduled Tribe and general domiciled students of Mizoram in undergraduate, diploma, and postgraduate courses.',
    benefitsSummary: 'Annual tuition reimbursement + monthly maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Mizoram'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST', 'General'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric higher education', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'residential_cert_mizoram', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Mizoram Scholarship Window',
        description: 'Complete registration on mizoram.gov.in with valid residential certificate.',
        requiredDocuments: ['aadhaar', 'residential_cert_mizoram', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://mizoram.gov.in',
      },
    ],
    sourceUrl: 'https://mizoram.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Mizoram',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'mizoram', 'education', 'post-matric'],
  },

  // 27. Sikkim
  {
    id: 'sikkim_post_matric_scholarship',
    name: 'Sikkim State Post-Matric Scholarship Scheme',
    aliases: ['Sikkim PMS'],
    department: 'Social Welfare Department',
    authority: 'Government of Sikkim',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee assistance and stipend for Sikkimese students pursuing post-matric courses in recognized institutions.',
    benefitsSummary: '100% compulsory tuition fee refund + maintenance allowance for hostellers and day scholars.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Sikkim'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-06-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'SC', 'ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies with Sikkim Subject / Certificate of Identification', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Parental annual income under ₹2.5 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'coi_sikkim', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Sikkim State Window',
        description: 'Complete registration on sikkim.gov.in with Certificate of Identification (COI).',
        requiredDocuments: ['aadhaar', 'coi_sikkim', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://sikkim.gov.in',
      },
    ],
    sourceUrl: 'https://sikkim.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Government of Sikkim Social Welfare Department',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'sikkim', 'education', 'post-matric'],
  },

  // 28. Arunachal Pradesh
  {
    id: 'arunachal_dhte_post_matric_st',
    name: 'Arunachal Pradesh Post-Matric Scholarship for APST Students',
    aliases: ['Arunachal APST Scholarship', 'DHTE Arunachal Scholarship'],
    department: 'Directorate of Higher & Technical Education (DHTE)',
    authority: 'Government of Arunachal Pradesh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Financial support covering tuition, book allowances, and maintenance for Arunachal Pradesh Scheduled Tribe (APST) students pursuing higher education.',
    benefitsSummary: '100% compulsory approved fees reimbursed + annual stipend up to ₹16,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Arunachal Pradesh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in accredited post-matric courses', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual parental income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'equals', value: 'ST', label: 'Arunachal Pradesh Scheduled Tribe (APST) certificate holder', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'apst_cert', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Arunachal DHTE Scholarship Portal',
        description: 'Submit online application on apdhte.nic.in with verified APST certificate.',
        requiredDocuments: ['aadhaar', 'apst_cert', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://apdhte.nic.in',
      },
    ],
    sourceUrl: 'https://apdhte.nic.in',
    applicationUrl: 'https://apdhte.nic.in',
    sourceAuthority: 'Government of Arunachal Pradesh DHTE',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'arunachal-pradesh', 'education', 'apst'],
  },
];
