import { GovernmentService } from '../../types';

export const UT_SCHEMES: GovernmentService[] = [
  // 1. Delhi
  {
    id: 'delhi_edistrict_post_matric_scholarship',
    name: 'Delhi e-District Post-Matric Scholarship for SC/ST/OBC/Minority Students',
    aliases: ['Delhi e-District Scholarship', 'Delhi PMS'],
    department: 'Department for the Welfare of SC/ST/OBC/Minorities',
    authority: 'Government of NCT of Delhi',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Full tuition fee reimbursement and maintenance allowance for domiciled students in Delhi belonging to SC, ST, OBC, and minority communities.',
    benefitsSummary: '100% course tuition fee reimbursement + monthly maintenance allowance up to ₹1,200.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Delhi'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC', 'Minority'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in recognized college or university in Delhi', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC', 'Minority'], label: 'Designated for SC, ST, OBC, or Minority students', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'delhi_residence_proof', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Delhi e-District Portal',
        description: 'Complete student registration on edistrict.delhigovt.nic.in using Aadhaar OTP verification.',
        requiredDocuments: ['aadhaar', 'delhi_residence_proof', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://edistrict.delhigovt.nic.in',
      },
    ],
    sourceUrl: 'https://edistrict.delhigovt.nic.in',
    applicationUrl: 'https://edistrict.delhigovt.nic.in',
    sourceAuthority: 'Government of NCT of Delhi',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'delhi', 'education', 'edistrict'],
  },

  // 2. Jammu and Kashmir
  {
    id: 'jk_social_welfare_scholarship',
    name: 'Jammu and Kashmir Post-Matric Scholarship Scheme for SC/ST/OBC',
    aliases: ['J&K Post Matric', 'JK Social Welfare Scholarship'],
    department: 'Social Welfare Department',
    authority: 'Government of Jammu and Kashmir (UT)',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric educational stipend and fee reimbursement for domiciled students belonging to SC, ST, OBC, and Pahari communities in J&K.',
    benefitsSummary: '100% compulsory educational fee reimbursement + monthly maintenance allowance.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Jammu and Kashmir'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2019-10-31',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in J&K', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual parental income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'ST', 'OBC'], label: 'Reserved for SC, ST, or OBC students of J&K', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'jk_domicile_cert', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through J&K Social Welfare Portal',
        description: 'Complete application on socialwelfarejk.nic.in with J&K Domicile Certificate.',
        requiredDocuments: ['aadhaar', 'jk_domicile_cert', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://socialwelfarejk.nic.in',
      },
    ],
    sourceUrl: 'https://socialwelfarejk.nic.in',
    applicationUrl: 'https://socialwelfarejk.nic.in',
    sourceAuthority: 'UT Administration of Jammu and Kashmir',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'jammu-kashmir', 'education', 'post-matric'],
  },

  // 3. Ladakh
  {
    id: 'ladakh_tribal_higher_education',
    name: 'Ladakh Post-Matric Scholarship Scheme for Scheduled Tribe Students',
    aliases: ['Ladakh ST Scholarship'],
    department: 'Social and Tribal Welfare Department',
    authority: 'Administration of Union Territory of Ladakh',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Centrally funded and UT-administered post-matric scholarship for resident Scheduled Tribe students of Leh and Kargil districts.',
    benefitsSummary: 'Full tuition and statutory fees covered + annual maintenance allowance up to ₹15,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Ladakh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2019-10-31',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric degree or professional course', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Parental annual income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'equals', value: 'ST', label: 'Resident ST certificate holder of UT Ladakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'ladakh_resident_cert', 'st_cert', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through UT Ladakh Welfare Portal',
        description: 'Submit registration on ladakh.gov.in under Social and Tribal Welfare Department.',
        requiredDocuments: ['aadhaar', 'ladakh_resident_cert', 'st_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://ladakh.gov.in',
      },
    ],
    sourceUrl: 'https://ladakh.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Administration of Union Territory of Ladakh',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'ladakh', 'education', 'st-scholarship'],
  },

  // 4. Chandigarh
  {
    id: 'chandigarh_edistrict_scholarship',
    name: 'Chandigarh Administration Post-Matric Scholarship for SC/OBC Students',
    aliases: ['Chandigarh Post Matric'],
    department: 'Department of Higher Education & Social Welfare',
    authority: 'Chandigarh Administration (UT)',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Financial support covering tuition, exam fees, and maintenance for domiciled SC and OBC students studying in UT Chandigarh colleges.',
    benefitsSummary: 'Full tuition fee reimbursement + monthly stipend for hostellers and day scholars.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Chandigarh'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in Chandigarh', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh for SC or ₹1.5 Lakh for OBC', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['SC', 'OBC'], label: 'Reserved for SC or OBC students of Chandigarh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'chandigarh_residence_proof', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Chandigarh Services Portal',
        description: 'Register on chdservices.gov.in with verified Chandigarh residence proof.',
        requiredDocuments: ['aadhaar', 'chandigarh_residence_proof', 'income_cert'],
        estimatedEffort: '20 minutes',
        isOnline: true,
        portalUrl: 'https://chdservices.gov.in',
      },
    ],
    sourceUrl: 'https://chdservices.gov.in',
    applicationUrl: 'https://chdservices.gov.in',
    sourceAuthority: 'Chandigarh Administration',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'chandigarh', 'education', 'post-matric'],
  },

  // 5. Puducherry
  {
    id: 'puducherry_edistrict_scholarship',
    name: 'Puducherry Government Post-Matric Financial Assistance Scheme',
    aliases: ['Puducherry PMS'],
    department: 'Adi Dravidar Welfare and Scheduled Tribes Department',
    authority: 'Government of Puducherry (UT)',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Post-matric tuition fee assistance and monthly maintenance grants for students belonging to SC, ST, and general economically weak categories in Puducherry.',
    benefitsSummary: '100% compulsory tuition and special fees paid + maintenance grant.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Puducherry'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-08-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['SC', 'ST', 'General'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric higher education in Puducherry', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Annual family income under ₹2.5 Lakh', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'puducherry_nativity_cert', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply on Puducherry e-District Portal',
        description: 'Complete registration on edistrict.py.gov.in with Nativity and Income certificates.',
        requiredDocuments: ['aadhaar', 'puducherry_nativity_cert', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://edistrict.py.gov.in',
      },
    ],
    sourceUrl: 'https://edistrict.py.gov.in',
    applicationUrl: 'https://edistrict.py.gov.in',
    sourceAuthority: 'Government of Puducherry',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'puducherry', 'education', 'edistrict'],
  },

  // 6. Andaman and Nicobar Islands
  {
    id: 'andaman_higher_education_scholarship',
    name: 'Andaman & Nicobar Islands Post-Matric Scholarship Scheme',
    aliases: ['Andaman Higher Education Scholarship'],
    department: 'Directorate of Higher Education',
    authority: 'Andaman & Nicobar Administration',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Higher education assistance and hostel allowance for island students pursuing post-matric studies in the islands or on mainland India.',
    benefitsSummary: 'Tuition reimbursement + monthly islander hostel and conveyance allowance up to ₹3,000.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Andaman and Nicobar Islands'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['General', 'OBC', 'ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies with A&N islander certificate', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 300000, label: 'Annual household income under ₹3.0 Lakh', isMandatory: false },
    ],
    requiredDocuments: ['aadhaar', 'islander_cert', 'income_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through A&N Administration Portal',
        description: 'Complete registration on andaman.gov.in with Islander Identity Certificate.',
        requiredDocuments: ['aadhaar', 'islander_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://andaman.gov.in',
      },
    ],
    sourceUrl: 'https://andaman.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Andaman & Nicobar Administration',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'andaman', 'education', 'higher-education'],
  },

  // 7. Dadra and Nagar Haveli and Daman and Diu
  {
    id: 'dnhdd_tribal_scholarship',
    name: 'DNHDD Post-Matric Scholarship for Scheduled Tribe & Backward Class Students',
    aliases: ['DNHDD Post Matric', 'Daman Diu Scholarship'],
    department: 'Directorate of Social Welfare',
    authority: 'Administration of Dadra and Nagar Haveli and Daman and Diu (UT)',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Financial assistance covering course fees and maintenance for domiciled students of DNH and Daman & Diu pursuing technical and higher education.',
    benefitsSummary: '100% tuition and statutory examination fees reimbursed + maintenance stipend.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Dadra and Nagar Haveli and Daman and Diu'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2020-01-26',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST', 'SC', 'OBC'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies in DNHDD or approved institutes', isMandatory: true },
      { field: 'annualIncome', operator: 'less_than_or_equal', value: 250000, label: 'Family annual income under ₹2.5 Lakh', isMandatory: true },
      { field: 'socialCategory', operator: 'in', value: ['ST', 'SC', 'OBC'], label: 'Reserved for ST, SC, or OBC students of DNHDD', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'dnhdd_domicile_cert', 'income_cert', 'caste_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Daman NIC Portal',
        description: 'Complete registration on daman.nic.in under Directorate of Social Welfare.',
        requiredDocuments: ['aadhaar', 'dnhdd_domicile_cert', 'income_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://daman.nic.in',
      },
    ],
    sourceUrl: 'https://daman.nic.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Administration of Dadra and Nagar Haveli and Daman and Diu',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'dnhdd', 'daman-diu', 'education'],
  },

  // 8. Lakshadweep
  {
    id: 'lakshadweep_post_matric_scholarship',
    name: 'Lakshadweep Administration Higher Education Scholarship for Island Students',
    aliases: ['Lakshadweep Island Scholarship'],
    department: 'Department of Education',
    authority: 'Administration of the Union Territory of Lakshadweep',
    category: 'education',
    secondaryCategories: ['financial_assistance'],
    description: 'Comprehensive financial support covering 100% course fees, hostel expenses, and mainland conveyance for resident Scheduled Tribe students of Lakshadweep.',
    benefitsSummary: '100% tuition, boarding, and annual mainland ship travel expenses covered.',
    jurisdictionLevel: 'STATE',
    applicableStates: ['Lakshadweep'],
    residenceRequired: true,
    studyLocationEligible: true,
    employmentLocationEligible: false,
    propertyLocationEligible: false,
    agricultureLocationEligible: false,
    businessLocationEligible: false,
    status: 'ACTIVE',
    effectiveFrom: '2016-07-01',
    officialVerificationStatus: 'OFFICIALLY_VERIFIED',
    verificationEvidence: 'OFFICIAL_PORTAL',
    eligibleCategories: ['ST'],
    eligibilityRules: [
      { field: 'isStudent', operator: 'boolean_true', value: true, label: 'Enrolled in post-matric studies with native Lakshadweep ST status', isMandatory: true },
      { field: 'socialCategory', operator: 'equals', value: 'ST', label: 'Native Scheduled Tribe of Union Territory of Lakshadweep', isMandatory: true },
    ],
    requiredDocuments: ['aadhaar', 'island_nativity_cert', 'st_cert', 'bank_passbook'],
    steps: [
      {
        stepNumber: 1,
        title: 'Apply through Lakshadweep UT Portal',
        description: 'Complete registration on lakshadweep.gov.in under Directorate of Education.',
        requiredDocuments: ['aadhaar', 'island_nativity_cert', 'st_cert'],
        estimatedEffort: '25 minutes',
        isOnline: true,
        portalUrl: 'https://lakshadweep.gov.in',
      },
    ],
    sourceUrl: 'https://lakshadweep.gov.in',
    applicationUrl: 'https://scholarships.gov.in',
    sourceAuthority: 'Administration of the Union Territory of Lakshadweep',
    sourceType: 'verified',
    sourceConfidence: 'High',
    lastVerified: '2026-08-30',
    version: '2026.1',
    tags: ['scholarship', 'lakshadweep', 'education', 'st-scholarship'],
  },
];
